# Shadow Editor Server Configuration for development

[server]
port = ":2020"                              # server address

[database]
type = "mongo"                              # only support mongo
host = "127.0.0.1"                          # mongo ip
port = 27017                                # mongo port
user = ""                                   # mongo username
password = ""                               # mongo password
database = "ShadowEditor"                   # mongo database name

[authority]
enabled = false                              # enable authority
expires = 120                               # login time, minutes, only support integer
secret_key = "Welcome ---------"            # secret_key is used to encrypt credentials

[upload]
max_size = 1000000000                       # max upload file size

[remote]
enabled = false                             # enable remote edit
web_socket_port = 5000                      # web socket server port

[path]
public_dir = "../build/public"              # The directory that contains index.html. 
                                            # Path `./public/Upload` need write authority.
log_dir = "./logs"                          # The directory that contains log files. Need write authority.

[log]
file = "./logs/ShadowServer.txt"